services:
  - type: web
    name: pw-poll-api
    runtime: node
    buildCommand: npm install && npm --prefix frontend install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
