services:
  - type: web
    name: pw-schedule-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FRONTEND_URL
        sync: false
